### ISSUE TITLE
Please don't color the brackets in comments

### ISSUE THREAD

**Issue by eladcandroid** [CoenraadS/BracketPair#57] opened 2017-11-28 07:33 UTC
Like here:
<img width="404" alt="screen shot 2017-11-28 at 9 32 21" src="https://user-images.githubusercontent.com/13297000/33307429-26fe27d6-d41f-11e7-96ae-fdd496d13754.png">

**Comment by CoenraadS** [comment] 2017-11-28 07:59
What language is this?

**Comment by eladcandroid** [comment] 2017-11-28 08:25
@CoenraadS JavaScript/TypeScript

**Comment by CoenraadS** [comment] 2017-11-28 08:28
Is that what it says in the status bar?

![image](https://user-images.githubusercontent.com/5593825/33309424-5df7f2ea-d41e-11e7-833c-8d9f87811a77.png)

Because it should be working for those languages. Else can you post a snippet that causes this so I can try to reproduce.

**Comment by eladcandroid** [comment] 2017-11-28 09:01
I have the same TS version. 

Your great extension works..
I'm talking about the comments that show the brackets in a pair color instead of show them in a gray color like the whole comment.

**Comment by CoenraadS** [comment] 2017-11-28 09:14
For me it is working though:

![image](https://user-images.githubusercontent.com/5593825/33311340-d45efe46-d424-11e7-9d37-12ed465b55a3.png)

So I'm not sure what is causing the coloring :(

**Comment by jserrao** [comment] 2017-12-28 16:43
Extended comment from one of my teaching JS files, also attached is the image of what it renders like. I'm using the Solarized-dark theme if that helps:

    /************
     * 
     * ### 3 ###
     * 
     * Array.prototype.sort()
     * Sort the inventors by birthdate, oldest to youngest
     * 
     * .sort() works a lot like .filter() and .map() but happened to be part of the JS spec way before ES6
     * You can use this one freely on Internet Explorer without worrying about Bill Gates knocking on your door for ActiveX insubordination
     * 
     * .sort() has a callback function with two arguments very much like .filter() and .map()
     * So the first way to think about .sort() is to think about it as a loop once again, another loop without all the `for` syntax hanging around
     * Each pass of the loop, it compares two items in the array sequentially, one after the other
     * 
     * the first argument is what you can think of as a first item to compare while the second argument would be the second item the first gets compared to
     * .sort() actually works differently on different browsers. The JS gods have a steering committee called ECMAScript that hasn't laid out a specific algorithm for sorting, so JS interpreters can sort however they like.
     * More here if you're really curious about the .sort() algorithm: https://stackoverflow.com/a/1494742
     * 
     * I think the easiest way to wrap your head around JS sorting is to picture each item getting selected, one by one. That selected item then gets compared to the item before it, and ordered in the array according to the condition you set. 
     * Most of the time, sort will likely be arranging items in ascending or descending order but perhaps you could use it for other things.
     * In our example, we're looking for the array to get sorted by the earliest year, so everytime firstArrayItem is bigger than secondArrayItem, we return 1. 
     * That is basically saying 'true' but in a way that can be compared by the algorithm inside .sort()
     */

<img width="913" alt="comment-bracket-highlighting" src="https://user-images.githubusercontent.com/947542/34416986-1d692c9a-ebc4-11e7-86e4-3b4236c4df2a.png">

**Comment by SanketDG** [comment] 2018-01-27 12:27
Happens in bash scripts for sure 

![image](https://user-images.githubusercontent.com/8980971/35471937-799f4164-038b-11e8-9d3f-b2cb5c273416.png)

**Comment by CoenraadS** [comment] 2018-02-24 15:09
Should be fixed in latest release

**Closed by CoenraadS** 2018-02-24 15:09 UTC

**Comment by jserrao** [comment] 2018-02-26 14:17
Confirmed on my end:

![bracket-highlighting-fix](https://user-images.githubusercontent.com/947542/36675040-e0fc4a8a-1ad5-11e8-9505-119887dbda8c.png)
