### ISSUE TITLE
BracketPair Settings: Prism.languages.extend is not a function

### ISSUE THREAD

**Issue by asliabir** [CoenraadS/BracketPair#100] opened 2018-03-22 18:03 UTC
![affsfdfsf](https://serving.photos.photobox.com/664341968e2afb649f19dd7870a7ae45fce0f95a64074ca8451c15ef0e197122fdc9b58d.jpg)

**Comment by PixelT** [comment] 2018-03-22 18:07
Duplicate https://github.com/CoenraadS/BracketPair/issues/98

**Comment by CoenraadS** [comment] 2018-03-22 18:15
Why does this happen :( 

Can you test what happens if you go to `%USERPROFILE%/.vscode/extensions` and delete all bracket pair folders?

**Comment by PixelT** [comment] 2018-03-22 18:21
I checked it.

> Can you test what happens if you go to %USERPROFILE%/.vscode/extensions and delete all bracket pair folders? Then reinstall the extension?
Didn't help

With version `1.0.20` it works ok, the notification appears on version `>=1.0.21`so I guess the reason is on changes between v20 and 21

**Comment by CoenraadS** [comment] 2018-03-22 18:24
No worries, I appreciate the help. One last thing to check, if you toggle developer tools and write `process.versions` in the console, what is the version of node?

**Comment by CoenraadS** [comment] 2018-03-23 06:46
Closing this issue because dupe of #98

**Closed by CoenraadS** 2018-03-23 06:46 UTC
