### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by capaj** [CoenraadS/BracketPair#10] opened 2017-01-23 15:21 UTC
when I was deleting a file, I got this error:
```
Uncaught Exception:  TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at t.validatePosition (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:3965)
    at t.offsetAt (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:3164)
    at Object.offsetAt (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:1747)
    at DocumentDecoration.updateDecorations (/home/capaj/.vscode/extensions/CoenraadS.bracket-pair-colorizer-0.2.1/out/src/documentDecoration.js:75:36)
    at Timeout._onTimeout (/home/capaj/.vscode/extensions/CoenraadS.bracket-pair-colorizer-0.2.1/out/src/documentDecoration.js:46:22)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

```

**Comment by CoenraadS** [comment] 2017-01-23 19:05
Thanks for the report, I'll see if I can reproduce it.

**Comment by CoenraadS** [comment] 2017-02-09 12:51
Hopefully this is fixed in the latest version. I say hopefully, because I could not find a consistent way to reproduce it. 

For some reason, sometimes a document reports it has a linecount of 0. I'm not sure what the cause is, but I just filter those documents out for now. If it still occurs feel free to reopen this issue.

**Closed by CoenraadS** 2017-02-09 12:51 UTC

**Comment by capaj** [comment] 2017-02-09 15:55
@CoenraadS I did not have a custom timeout setting.

THanks for the new release! Will take it for a spin, if it exhibits anymore, I'll reopen.
